# Generated by Django 4.2.7 on 2023-12-05 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_register', models.DateField(default=datetime.date(2023, 12, 5))),
                ('date_of_collection', models.DateField()),
                ('amount_charged', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('balance', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('sleeve', models.FloatField()),
                ('armhole', models.FloatField()),
                ('biceps', models.FloatField()),
                ('wrist', models.FloatField()),
                ('bust', models.FloatField()),
                ('shirt_length', models.FloatField()),
                ('waist', models.FloatField()),
                ('lap', models.FloatField()),
                ('stamina', models.FloatField()),
                ('ankle', models.FloatField()),
                ('neck', models.FloatField()),
                ('links', models.FloatField()),
                ('freehand', models.FloatField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='customer_pictures/')),
                ('total_sets', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('paid', 'Paid'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
