# Generated by Django 4.2.7 on 2023-12-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_trouser_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='customer_pictures/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('paid', 'Paid'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='customer.customer')),
                ('pictures', models.ManyToManyField(blank=True, to='customer.image')),
            ],
        ),
    ]
