# Generated by Django 4.2.7 on 2023-12-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_image_description_remove_image_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pictures',
        ),
    ]
