# Generated by Django 4.2.7 on 2023-12-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_image_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_pictures', to='customer.customer')),
                ('pictures', models.ManyToManyField(blank=True, to='customer.image')),
            ],
        ),
    ]
