# Generated by Django 4.2.7 on 2023-12-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_multipleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='customer.image'),
        ),
        migrations.DeleteModel(
            name='MultipleImage',
        ),
    ]
