# Generated by Django 4.2.7 on 2023-12-06 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_image_pictures_delete_multipleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_register',
            field=models.DateField(default=datetime.date(2023, 12, 6)),
        ),
    ]
