# Generated by Django 4.2.7 on 2023-12-08 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_date_of_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_register',
            field=models.DateField(default=datetime.date(2023, 12, 8)),
        ),
    ]
