# Generated by Django 4.2.7 on 2023-12-22 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customer_date_of_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ankle',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='armhole',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='biceps',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bust',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_register',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='freehand',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lap',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='links',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='neck',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shirt_length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shoulder',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sleeve',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stamina',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='trouser_length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='waist',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wrist',
            field=models.FloatField(default=0),
        ),
    ]
