# Generated by Django 4.2.7 on 2023-12-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customer_amount_paid_alter_customer_ankle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='trouser_length',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
